// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASo1917_piGD5f-cgJciv_hs8FanHRZ3s',
    appId: '1:918146294693:web:20f23696108e2c23593e4c',
    messagingSenderId: '918146294693',
    projectId: 'cusco360-51497',
    authDomain: 'cusco360-51497.firebaseapp.com',
    storageBucket: 'cusco360-51497.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFZY8FmZ1vcwqkBwqCPA1LMvrTr7frDB4',
    appId: '1:918146294693:android:42e0183a2afb4859593e4c',
    messagingSenderId: '918146294693',
    projectId: 'cusco360-51497',
    storageBucket: 'cusco360-51497.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASo1917_piGD5f-cgJciv_hs8FanHRZ3s',
    appId: '1:918146294693:web:d1fa1eaea133dbaf593e4c',
    messagingSenderId: '918146294693',
    projectId: 'cusco360-51497',
    authDomain: 'cusco360-51497.firebaseapp.com',
    storageBucket: 'cusco360-51497.firebasestorage.app',
  );
}
